from pathlib import Path
from types import ModuleType
from typing import NamedTuple, Self

from pyochain import Iter

SCAN_DOC = """All nodes that represent logical scan sources.

The `Scan` union is generated from all public `BaseNode` subclasses with names starting with `Scan`.
"""

NODE_DOC = """All nodes that can be part of the logical plan.

Each node represents a logical operation to be performed on the data, such as filtering, joining, or aggregating.

They just hold the input arguments for the operation, and are used to build the logical plan before it's compiled into executable code.

Note:
    - `Node` is a type alias for the union of all public `Node` subclasses.
    - `BaseNode` is the base class for all nodes, but should not be used directly.

    We do this because Python does not have built-in support for Enums with associated data like Rust does.

    Using dataclasses for each node allows us to easily store the necessary information for each operation,

    while still being able to treat them as a unified type when building the plan, relying on the type checker to ensure exhaustiveness when matching on them.
"""
THEME_DOC = (
    """Themes available for SQL syntax highlighting in the `sql_query` method."""
)


def generate_themes(caller: Path) -> tuple[int, Path]:
    from pygments.styles._mapping import (  # pyright: ignore[reportMissingTypeStubs]  # noqa: PLC2701
        STYLES,
    )

    from src.belugas import typing as typing_module

    dest = _resolve_module_path(typing_module)
    content = (
        Iter(STYLES.values()).map_star(lambda _, style, __: f'"{style}"').join(" ,")
    )
    content = f"Themes = Literal[{content}]"

    return (
        _build_content(
            dest,
            caller,
            "# theme marker START",
            "# theme marker END",
            content,
            THEME_DOC,
        ),
        dest,
    )


def generate_nodes(caller: Path) -> tuple[int, Path]:
    from src.belugas._plan import nodes as node_module  # noqa: PLC2701

    dest = _resolve_module_path(node_module)

    def all_subclasses(cls: type) -> Iter[type]:
        def _subcls() -> Iter[type]:
            return Iter(cls.__subclasses__())

        return _subcls().chain(_subcls().flat_map(all_subclasses))

    def _render_type_name(cls: type) -> str:
        if cls.__name__ == "ScanInMemory":
            return "ScanInMemory[IntoRel]"

        return cls.__name__

    scan_content, node_content = (
        all_subclasses(node_module.BaseNode)
        .filter(lambda cls: not cls.__name__.startswith("_"))
        .map(_render_type_name)
        .unique()
        .sort()
        .iter()
        .partition(lambda name: name.startswith("Scan"))
    )
    scan_content = f"type Scan = ({scan_content.iter().join(' | ')})"
    node_content = f"Node = ({node_content.iter().join(' | ')})"

    _ = _build_content(
        dest,
        caller,
        "# plan scan marker START",
        "# plan scan marker END",
        scan_content,
        SCAN_DOC,
    )

    return (
        _build_content(
            dest,
            caller,
            "# plan node marker START",
            "# plan node marker END",
            node_content,
            NODE_DOC,
        ),
        dest,
    )


def _resolve_module_path(module: ModuleType) -> Path:
    file_path = module.__file__
    if file_path is None:
        msg = f"Could not resolve destination path for module: {module.__name__}"
        raise RuntimeError(msg)

    return Path(file_path)


def _build_content(  # noqa: PLR0913, PLR0917
    dest: Path, caller: Path, start_marker: str, end_marker: str, content: str, doc: str
) -> int:
    warning = _warning(caller)
    file_content = dest.read_text(encoding="utf-8")
    idxs = Indexes.new(file_content, start_marker, end_marker)
    new_content = f"""
{file_content[: idxs.start + len(start_marker)]}
{content}
'''{doc}
{warning}'''
{file_content[idxs.end :]}"""
    return dest.write_text(new_content, encoding="utf-8")


class Indexes(NamedTuple):
    start: int
    end: int

    @classmethod
    def new(cls, file_content: str, start_marker: str, end_marker: str) -> Self:
        start_idx = file_content.find(start_marker)
        end_idx = file_content.find(end_marker)
        return cls(start_idx, end_idx)


def _warning(caller: Path) -> str:
    return f"""
Dynamically generated by `{caller.as_posix()}`.

Do NOT edit manually.
"""
