from pathlib import Path
from typing import NamedTuple, Self

from pyochain import Iter


def generate_themes(caller: Path, dest: Path) -> int:
    from pygments.styles._mapping import (  # pyright: ignore[reportMissingTypeStubs]  # noqa: PLC2701
        STYLES,
    )

    content = (
        Iter(STYLES.values()).map_star(lambda _, style, __: f'"{style}"').join(" ,")
    )
    content = f"Themes = Literal[{content}]"

    doc = """Themes available for SQL syntax highlighting in the `sql_query` method."""

    return _build_content(
        dest, caller, "# theme marker START", "# theme marker END", content, doc
    )


def generate_nodes(caller: Path, dest: Path) -> int:
    from src.belugas._plan import nodes  # noqa: PLC2701

    def all_subclasses(cls: type) -> Iter[type]:
        def _subcls() -> Iter[type]:
            return Iter(cls.__subclasses__())

        return _subcls().chain(_subcls().flat_map(all_subclasses))

    content = (
        all_subclasses(nodes.Node)
        .map(lambda cls: cls.__name__)
        .filter(lambda name: not name.startswith("_"))
        .unique()
        .sort()
        .join(" | ")
    )
    content = f"PlanNode = ({content})"

    doc = """All public `Node` subclasses.."""

    return _build_content(
        dest, caller, "# plan node marker START", "# plan node marker END", content, doc
    )


def _build_content(  # noqa: PLR0913, PLR0917
    dest: Path, caller: Path, start_marker: str, end_marker: str, content: str, doc: str
) -> int:
    warning = _warning(caller)
    file_content = dest.read_text(encoding="utf-8")
    idxs = Indexes.new(file_content, start_marker, end_marker)
    new_content = f"""
{file_content[: idxs.start + len(start_marker)]}
{content}
'''{doc}
{warning}'''
{file_content[idxs.end :]}"""
    return dest.write_text(new_content, encoding="utf-8")


class Indexes(NamedTuple):
    start: int
    end: int

    @classmethod
    def new(cls, file_content: str, start_marker: str, end_marker: str) -> Self:
        start_idx = file_content.find(start_marker)
        end_idx = file_content.find(end_marker)
        return cls(start_idx, end_idx)


def _warning(caller: Path) -> str:
    return f"""
Dynamically generated by `{caller.as_posix()}`.

Do NOT edit manually.
"""
